version: '3.1'

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: example
  redis:
    container_name: redis
    image: redis
    volumes:
      - ./storage/redis/data:/data
    ports:
      - "6379:6379"
    restart: always
  web:
    user: "1001:1001"
    build: .
    command: bash -c "python3 /code/manage.py migrate --noinput && python3 /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
     - "8000:8000"
    depends_on:
     - db
  celery-beat:
    build: .
    command: celery -A project11 beat -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: celery -A project11 worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  